--require('init/packer')
require('config.lazy')
--require('plugin/packer_plugins')
--require('plugin/lsp/lsp')
--require('plugin/nvim-tree')
--require('plugin/telescope')
--require('plugin/catppuccin')
--require('plugin/treesitter')
-- require('plugin/vim-comp')
--require('plugin/devicons')
--require('plugin/zero-lsp')
--require('plugin/nvim-notify')
--require('scripts/handlers')
require('config.config')
require('config.mappings')
require('config.lsp-config')
require('config.cmp')
